nn_cfg:
  lr: 1e-3
  method: adam
  intermediate_layer_sizes: [500, 500]
  batch_size: 100
  epochs: 1e6

data:
  datetime: ''

train_unrolls: 10
eval_unrolls: 10
eval_every_x_epochs: 30
save_every_x_epochs: 1
test_every_x_epochs: 1
write_csv_every_x_batches: 1
epochs_jit: 2
N_train: 50000
N_test: 100
# num_samples: 1000
num_samples_train: 100
num_samples_test: 100
supervised: True
plot_iterates: [0, 5, 9]
loss_method: 'fixed_k'


accuracies: [.1, .01, .001, .0001]
skip_startup: False

pac_bayes_flag: False
load_weights_datetime: '2024-09-11/15-36-37'
nn_load_type: stochastic

pac_bayes_cfg:
  init_var: 1e-2
  c: 100.0
  b: 100
  delta: 0.00001
  delta2: 0.00001
  rep: True
  penalty_coeff: 1.0
  deterministic: False
  frac_solved_accs: nmse_full
  target_pen: 0.01
  skip_full: False
  pac_bayes_num_samples: 20000
lambd: 0.1
save_weights_flag: True
algo: alista