# to adjust for paper results
N_train: 1000 # number of samples
custom_loss: False # False is for the fixed-point residual, True for the max Euclidean distance

pac_bayes_cfg:
  delta: 0.0001
  gp: True
  frac_solved_accs: fp_full # for nmse use 'nmse_full', for fixed-point residual use 'fp_full'

# there is no need to change any of the values below
data:
  datetime: ''
eval_unrolls: 500

classical: True # do not change

# for visualizing
iterates_visualize: [10, 20, 50, 90, 200, 300, 500, 1000] #[10, 20, 50, 100, 200, 500]
vis_num: 0

# used for logging and plotting (not very important)
plot_iterates: [0, 10, 20]
accuracies: [1, .1, .01, .001, .0001]