output_datetimes:
- 2024-04-02/07-25-28

loss_overlay_titles: []
nearest_neighbor_datetime:  ''
pretrain_datetime: 2024-03-31/15-52-10
cold_start_datetime: ''
eval_iters: 11
accuracies: maml_full

percentile_dt: 2024-03-31/15-52-10 #(pretrain)

plot_acc_list: [0.501187, 1.0, 1.995262]
# custom_loss: False
custom_loss: True

maml_pretrain_visualization_dt: 2024-02-10/18-20-34
maml_visualization_dt: 2024-02-10/21-31-45

percentile_datetime_list: [2024-04-02/07-25-28]
