output_datetimes:
- 2024-04-16/09-35-22



loss_overlay_titles: []
nearest_neighbor_datetime: 2024-04-16/09-35-22
pretrain_datetime: ''
cold_start_datetime: 2024-04-16/09-35-22
eval_iters: 801 #501
accuracies: fp_full



plot_acc_list: [0.01, 0.001, 0.0001]

worst_case_datetime: 2024-02-05/12-05-50

worst_case: True

percentile_datetime_list: [2024-04-16/09-35-22]
percentile_dt: 2024-04-16/09-35-22
percentile_nn_dt: 2024-04-16/09-35-22
percentiles: [30, 50, 80, 90]
plot_indices: [0, 2, 3]

custom_loss: False